# TODO: work in progress

version: "3"
services:
  postgres:
    image: postgres:12.2
    ports:
      - "6432:5432"
    command: -c ssl=on -c ssl_cert_file=/var/lib/postgresql/certs/server.crt -c ssl_key_file=/var/lib/postgresql/certs/server.key -c log_statement=all -c log_directory=/tmp -c logging_collector=on -c log_connections=on -c log_min_error_statement=error
    volumes:
      # - "./files/cert/server.crt:/var/lib/postgresql/server.crt"
      # - "./files/cert/server.key:/var/lib/postgresql/server.key"
      # https://stackoverflow.com/a/68911338
      - ./data/:/var/lib/postgresql/data
      - ./postgres-initdb:/docker-entrypoint-initdb.d/
      - ./postgres-certs/:/var/lib/postgresql/certs/
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
      - POSTGRES_ROOT_PASSWORD=root
    # command: sleep 500000
